### ISSUE TITLE
GLText::protectJavascript() sometimes substitutes the same marker for multiple <script> tags

### ISSUE THREAD

**Issue by StuYarrow** [Geeklog-Core/geeklog#783]
The protectJavascript() function replaces a set of script tags and their contents with a string of the form `__SCRIPT_nnnnnnnnnnnnnn_MARKER__` where nnnnnnnnnnnnnn is the time since the epoch in tenths of milliseconds.  This often results in identical markers being inserted for script tags that are processed in quick succession.

The symptoms are described in this forum post:
https://www.geeklog.net/forum/viewtopic.php?showtopic=96492

**Comment by eSilverStrike** [comment]
Good find. This happens in articles and staticpages.

Here is a quote from the above forum post explaining how to reproduce the issue:

Create a story with the following body content:
PHP Formatted Code
```
<script>foo</script>
<script>bar</script>
 ```
Save the story and navigate to it. If the page source is viewed, the contents of the story body appear as:
PHP Formatted Code
```
<script>foo</script>
<script>foo</script>
``` 
Basically the contents of the first script tag are copied into all the subsequent tags.

The issue is appearing for me in a static page with 3 script tags driving a javascript gallery, and in this case the same mangling is also happening when I save the page via the (basic) editor. If I restore the correct content by editing the DB directly then it appears correctly in the editor until it is saved using the editor, at which point it gets mangled. The mangled version appears in the output HTML every time.

**Comment by dengenxp** [comment]
This was probably fixed with change set 11123d3.

**Comment by eSilverStrike** [comment]
I just checked by adding to an article:
```
<script>foo</script> <script>bar</script> 
```
Looking at the source I still see

```
<script>foo</script> <script>foo</script> 
```

so that commit didn't fix it.

**Comment by StuYarrow** [comment]
As far as I can tell, it has fixed the problem for me.

**Comment by eSilverStrike** [comment]
Not me, uniqid() is creating the same id which can be an issue according to: http://php.net/manual/en/function.uniqid.php

Using rand(0, 999) instead of uniqid() works for me but then again there is the chance of generating the same id especially with the more <script> tags you have.

We need a better random generator. There are a few other examples from comments on the php uniqid page which might meet our needs and fit in the requirements of Geeklog.

**Comment by dengenxp** [comment]
I fixed with change set df59c80 again.

**Comment by eSilverStrike** [comment]
Confirmed. I was just about to add a similar fix. 👍

**Comment by eSilverStrike** [comment]
Ivy has reported that autotags don't work in <script> tags anymore.
```
<script>
[xxxx:xxx]
</script>
```

**Comment by eSilverStrike** [comment]
@dengenxp Is there any reason why we are protecting the script tags from the function PLG_replaceTags when it replaces autotags? Was it messing with the javascript in some cases? Ivy is using autotags in staticpages with script tags (see forum post for more info above) in Geeklog 2.1.1 and can't anymore in Geeklog 2.1.2.

**Comment by eSilverStrike** [comment]
@mystralkk do you see any reason for protecting the javascript from the PLG_replaceTags function? We allowed it before in previous versions of Geeklog and I guess a few people did it as it has been requested again.

**Comment by mystralkk** [comment]
Since we allowed the use of autotags anywhere including JavaScript code snippets, the PLG_replaceTags function doesn't need to protect the script tag.  I myself won't use autotags in JavaScript, though.

**Comment by eSilverStrike** [comment]
Same here but I will remove the protection then since others have requested it.
